### ISSUE TITLE
Presentacions anteriors

### ISSUE THREAD

**Issue by XaviTorello** [floss-talks-andorra/xerrades#3]
@francrodriguez hi ha documentació de suport (ppts, pdfs, ...) de les xerrades anteriors?

**Comment by francrodriguez** [comment]
No hi ha documentació de les sessions anteriors.
Es va fer un resum en el blog andfree.org , però el propietari de dit domini va tenir un problema i tot s'ha perdut.

**Comment by XaviTorello** [comment]
Llàstima, he mirat a archive.org però no he sapigut trobar gaire informació, només un petit resum de la primera trobada.
